# Generated by Django 3.1.3 on 2021-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=20)),
                ('complaintype', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
